using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using Photon.Realtime;
using UnityEngine.UI;

// MonoBehaviourPunCallbacksを継承して、PUNのコールバックを受け取れるようにする
public class TestScene : MonoBehaviourPunCallbacks
{

    public static GameObject My; //自身のアバターを格納
  
    public Text PlayerNum;

    public int Number;

    private void Start()
    {
        PhotonNetwork.NickName = "Player";
        Number = 0;

        // PhotonServerSettingsの設定内容を使ってマスターサーバーへ接続する
        PhotonNetwork.ConnectUsingSettings();
    }

    // マスターサーバーへの接続が成功した時に呼ばれるコールバック
    public override void OnConnectedToMaster()
    {
        // "TestRoom"という名前のルームに参加する（ルームが存在しなければ作成して参加する）
        PhotonNetwork.JoinOrCreateRoom("TestRoom", new RoomOptions(), TypedLobby.Default);
        //base.OnConnectedToMaster();
    }

    // ゲームサーバーへの接続が成功した時に呼ばれるコールバック
    public override void OnJoinedRoom()
    {
        // ランダムな座標に自身のアバター（ネットワークオブジェクト）を生成する
        var position = new Vector3(Random.Range(-3f, 3f), Random.Range(-3f, 3f));
        My = PhotonNetwork.Instantiate("Avatar", position, Quaternion.identity);
        var local = PhotonNetwork.LocalPlayer;

        Debug.Log(local.ActorNumber);
        Number = local.ActorNumber; //何番目のプレイヤーかを保存
        //Time.timeScale = 0;

    }


    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Return))
        {
            My.gameObject.transform.Rotate(new Vector3(0, 0, 10));
        }
    }
}
